mappings:
- actions:
    action:
      class: SendOSC
      data:
      - [float, control.value]
      event: control_change
      path: /vis/smilies/{control.n}/amount
    class: SingleAction
  name: 'Smiley Amount #1'
  sources:
  - class: GridSlider
    controls:
      n__in: [0, 2, 4, 6]
      type: slider
- actions:
    action:
      class: SendOSC
      data:
      - [float, control.value]
      event: control_change
      path: /vis/smilies/{control.n}/alpha
    class: SingleAction
  name: 'Smiley Alpha #1'
  sources:
  - class: GridSlider
    controls:
      n__in: [1, 3, 5, 7]
      type: slider
- actions:
    action:
      class: SendOSC
      data:
      - [float, control.value]
      event: control_change
      path: /vis/master/alpha
    class: SingleAction
  name: Master Alpha
  sources:
  - class: GridSlider
    controls: {n: 8, type: slider}
- actions:
    class: StartStopAction
    end: {class: SendOSC, event: release, led: grey, path: '/vis/smilies/{control.n}/stop_emit'}
    start: {class: SendOSC, event: press, led: red, path: '/vis/smilies/{control.n}/start_emit'}
  name: 'Smiley Control #2'
  sources:
  - class: GridButton
    controls: {type: clip}
plugins: [send_osc]
settings:
  send_osc: {target: 'localhost:1234'}